pipeline{
    agent any
    tools{
        maven 'M2_HOME'
    }

    stages{
        stage('maven'){
            steps{
            sh 'mvn clean validate compile install test package' 

            }
        }

        stage('sonar-scan'){
            steps{
                sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=mopaul873_geo-app'

            }
        }


        stage('upload artifact'){
            steps{
                sh 'curl -uadmin:AP8gcgmmset5jeYChTJYDN6XmDd -T \
            target/bio*.jar \
            "http://ec2-54-237-58-39.compute-1.amazonaws.com:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"'
            }
        }
        
    }
}