pipeline{
    agent any
    tools{
        maven 'M2_HOME'
    }

    stages{
        stage('maven'){
            steps{
            sh 'mvn clean validate compile install test package' 

            }
        }
        stage('upload artifact'){
            steps{
                sh 'curl -u<USERNAME>:<PASSWORD> -T \ target/bio*,jar \ "http://54.237.58.39:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"'
            }
        }
        
    }
}